updated main.yml 7

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -15,6 +15,7 @@ jobs:
               with:
                 username: ${{ secrets.DOCKER_USERNAME }}
                 password: ${{ secrets.DOCKER_PASSWORD }}
+                
             - name: Set up Docker Build
               uses: docker/setup-buildx-action@v2
 
@@ -28,3 +29,22 @@ jobs:
 
             - name: Done
               run: echo "Image pushed to Docker Hub!"
+
+            - name: Deploy to EC2 via SSH
+              uses: appleboy/ssh-action@v1.0.0
+              with:
+                host: ${{ secrets.EC2_HOST }}
+                username: ${{ secrets.EC2_USER }}
+                key: ${{ secrets.EC2_SSH_KEY }}
+                script: |
+                    echo "Checking docker installation"
+                    if command -v docker &> /dev/null; then
+                        echo "Docker installation found"
+                    else
+                        echo "Docker installation not found. Installing Docker."
+                        curl https://get.docker.com | bash
+                        exit 1
+                    fi
+                    docker pull ${{ secrets.DOCKER_USERNAME }}/my-node-app-cicd:${{ github.sha }}
+                    docker stop myapp || true && docker rm myapp || true
+                    docker run -d --name myapp -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/my-node-app-cicd:${{ github.sha }}
